#!/bin/bash

echo "deb http://apt.anybox.fr/openerp common main" | sudo tee -a /etc/apt/sources.list
sudo apt-key adv --keyserver hkp://subkeys.pgp.net --recv-keys 0xE38CEB07
sudo aptitude update
sudo aptitude install openerp-server-system-build-deps
wget https://raw.github.com/buildout/buildout/master/bootstrap/bootstrap.py
virtualenv sandbox
sandbox/bin/pip uninstall -y setuptools pip
sandbox/bin/python bootstrap.py
git config --global user.email admin@seedoo.it
git config --global user.name seedoo
bin/buildout
